### ISSUE TITLE
@import UIKit doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [MatiBot/MBCircularProgressBar#16]
Of course I can fix it by replacing @import -> #import but you could fix it too

**Comment by tinbert** [comment]
I ran into the same issue. Here's my solution: check this in project settings

![modules](https://cloud.githubusercontent.com/assets/1325237/15038227/3fdd7cba-12a2-11e6-8628-8ba7ad6580b3.png)

I don't know yet where's the advantage of @import above #import, but there certainly is one ;-)
